In [1]:
import pandas as pd

In [2]:
movies_df = pd.read_csv("/Users/felipepesantez/Documents/development/datasets/recommend_systems/archive/movies.csv")
rating_df = pd.read_csv("/Users/felipepesantez/Documents/development/datasets/recommend_systems/archive/ratings.csv")

In [3]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
rating_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
def set_col_mapping(df, col_type):
    object_columns = df.select_dtypes(include=[col_type]).columns.tolist()
    print(object_columns)
    for col in object_columns:
        res = {}
        for x, value in enumerate(df[col].value_counts().index.tolist()):
            res[value] = x
        print(res)
        df[col] = df[col].map(res)

    return df

In [6]:
mv_df = set_col_mapping(movies_df, 'object')
rt_df = set_col_mapping(rating_df, 'object')

['title', 'genres']

In [7]:
mv_df.head()

   movieId  title  genres
0        1     40     115
1        2   6088      64
2        3   6490       3
3        4   6491       6
4        5   6492       1

In [8]:
merged_df = pd.merge(mv_df, rt_df, on="movieId")

In [9]:
merged_df.head()

   movieId  title  genres  userId  rating   timestamp
0        1     40     115       1     4.0   964982703
1        1     40     115       5     4.0   847434962
2        1     40     115       7     4.5  1106635946
3        1     40     115      15     2.5  1510577970
4        1     40     115      17     4.5  1305696483

In [10]:
sample_df = merged_df.drop(["title", "genres", "timestamp"], axis=1)

In [11]:
sample_df.to_csv("simple_df.csv", index=False)

In [12]:
sample_df.head()

   movieId  userId  rating
0        1       1     4.0
1        1       5     4.0
2        1       7     4.5
3        1      15     2.5
4        1      17     4.5